artifact_location: /home/adminadmin/brain_dir/combined_brain_dataset/runs/mlflow/214358605845146683
creation_time: 1766734250604
experiment_id: '214358605845146683'
last_update_time: 1766734250604
lifecycle_stage: active
name: /home/adminadmin/brain_dir/dir_brain_tessssst
