artifact_location: /home/adminadmin/brain_dir/combined_brain_dataset/runs/mlflow/0
creation_time: 1766734250594
experiment_id: '0'
last_update_time: 1766734250594
lifecycle_stage: active
name: Default
